[DRAFT] Buddies feature
seatsurfing/backend pull request #212
Opened 2024-01-07 21:25 UTC by dorumd

When using the product, we've realised it's missing one very handy capability: seeing where are your buddies sitting. In this MR, a new REST API to store / remove / list buddies is added and FE changes to display with a different shade the bookings made by buddies(on search page), adding a new buddy(on search page) and a new page to manage buddies list(view & remove).

2024-01-07 21:29 UTC, dorumd commented on server/buddy-router.go
> +func (router *BuddyRouter) getAll(w http.ResponseWriter, r *http.Request) {
The BE is missing tests, to be added.

2024-01-07 21:33 UTC, dorumd commented on booking-ui/src/styles/Search.css
> +    background-color: rgba(36, 21, 197, 0.9) !important;
I chose this color but not really familiar with accessibility impact, happy to change with another shade / color.

2024-01-14 12:45 UTC, dorumd commented
@virtualzone Hello! I believe this feature is now ready for review. Happy to hear your thoughts.

2024-01-20 12:34 UTC, virtualzone commented on server/buddy-router.go
> +		SendUpdated(w)
I guess SendNotFound() is more suitable here.

2024-01-20 12:35 UTC, virtualzone commented on server/buddy-router.go
> +	if err := GetBuddyRepository().Delete(e); err != nil {
A check whether the buddy belongs to the request user is necessary here.

2024-01-20 12:38 UTC, virtualzone requested changes
Hi @dorumd, thanks for this great enhancement! Please take a look at my comments in the ```buddy-router.go``` file.

2024-01-20 13:31 UTC, dorumd commented on server/buddy-router.go
> +func (router *BuddyRouter) create(w http.ResponseWriter, r *http.Request) {
In this case we have a create of a "Buddy" resource, why do you think an update & PUT is necessary?

2024-01-20 13:39 UTC, dorumd commented
Thanks for the feedback! @virtualzone Replied & fixed where required. I also noticed the version for go I used to test was newer and had slices as part of standard library, so I replaced it with a helper function instead in `main_test.go`.

2024-01-20 16:50 UTC, virtualzone approved these changes

2024-01-20 16:50 UTC, merged